spring:
 datasource:
  username: clothing_article
  password: clothing_article
  url: jdbc:mysql://localhost:3306/clothing_article
  
 jpa:
  hibernate:
   ddl-auto: none
  show-sql: true
  
 sql:
  init:
   mode: never
   